drop table if exists message cascade;
drop table if exists object_type cascade;
drop table if exists users cascade;


create sequence hibernate_sequence start 1 increment 1;
create table message (id int8 not null, code varchar(255), date timestamp, text varchar(255), user_id int8, primary key (id));
create table object_type (id int8 generated by default as identity, code varchar(255), primary key (id));
create table users (id int8 generated by default as identity, age int4 not null, name varchar(255), type_id int8, primary key (id));
create table information (id int8 generated by default as identity, main_information varchar(255), type varchar(255), primary key (id));

alter table if exists message add constraint FKpdrb79dg3bgym7pydlf9k3p1n foreign key (user_id) references users;
alter table if exists users add constraint FK2t1bxrgmnitevdj1c17x5nesa foreign key (type_id) references object_type;
